### ISSUE TITLE
Devices not registering / push not advertised

### ISSUE THREAD

**Issue by adamcandy** [st3fan/dovecot-xaps-daemon#12]
This is an exciting project - and I'd like to contribute.

I am running Dovecot 2.0.19, with the map_xaps_plugin.so dynamically loaded in - I see:
```
Jul 19 18:36:44 myhostname dovecot: imap: Debug: Module loaded: /usr/lib/dovecot/modules/imap_xaps_plugin.so
```
I have the dovecot-xaps-daemon running fine, with a push certificate that looks fine (although needed the updated entrust certificate for the openssl check).  With debugging on, I see:
```
$ dovecot-xaps-daemon bin/xapsd -key=/home/myusername/.applepush/key.pem -certificate=/home/myusername/.applepush/certificate.pem -database=/home/myusername/.applepush/xapsd.json -socket=/tmp/xapsd.sock -debug=true
2015/07/19 18:23:46 [DEBUG] Opening database at /home/myusername/.applepush/xapsd.json
2015/07/19 18:23:46 [DEBUG] Listening on UNIX socket at /tmp/xapsd.sock
2015/07/19 18:23:46 [DEBUG] Parsing /home/myusername/.applepush/certificate.pem to obtain APNS Topic
2015/07/19 18:23:46 [DEBUG] Topic is com.apple.mail.XServer....my_long_topic_hash....
2015/07/19 18:23:46 [DEBUG] Creating APNS client to gateway.push.apple.com:2195
2015/07/19 18:23:47 Starting xapsd 1.0b1 on /tmp/xapsd.sock
2015/07/19 18:24:25 [DEBUG] Accepted a connection
2015/07/19 18:24:25 [DEBUG] Received request: NOTIFY dovecot-username="myusername"	dovecot-mailbox="INBOX"
2015/07/19 18:24:25 [DEBUG] Returning success: 
```
All looks fine - except I do not see iOS devices discovering that the server supports Push (only 'fetch' and 'manual' on the account), and the JSON file is not updated by the daemon with account details and tokens.  The daemon appears to be listening and hears connections through the socket.  There is an established connection to 2195 (confirmed with netstat).  It looks like an issue with the registration of devices?  Advertising push services?  A port access issue?  What am I missing?

Thank you for your help - any comments or suggestions welcome!

**Comment by adamcandy** [comment]
This appears to have been entirely an issue with the client: iOS 8.3, with documented issues with push mail.  Upgrading to 8.4 has solved this, with push advertised and devices registered.  It is now working very well - a great project @st3fan !

**Comment by st3fan** [comment]
Interesting. Thanks for investigating this @adamcandy ! I looked at it but i could not repro this and gave up in frustration. But I recently switched to iOS 9 beta on my devices and I think things work much more stable there now also.
