### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by st3fan** [st3fan/dovecot-xaps-daemon#15]
Found the following in my logs:

```
2015/09/11 15:23:14 Failed to accept connection:
    accept unix /tmp/xapsd.sock: too many open files
```

**Comment by st3fan** [comment]
Not sure if this was reported for the Python or Go version.

**Comment by freswa** [comment]
I doubt this is still relevant since this is open for 2 years without someone else commenting. Will reopen in case this occurs again.
