### ISSUE TITLE
Daemon claims success, but device does not receive notification, xaps_plugin has error

### ISSUE THREAD

**Issue by anaoum** [st3fan/dovecot-xaps-daemon#16]
Hello

From the daemon:
```
2015/10/30 00:32:52 [DEBUG] Accepted a connection
2015/10/30 00:32:52 [DEBUG] Received request: NOTIFY dovecot-username="andrew"  dovecot-mailbox="INBOX"
2015/10/30 00:32:52 [DEBUG] Sending notification to RED-ACT-ED / REDACTED
2015/10/30 00:32:52 [DEBUG] Returning success:
```
However, this notification never shows up on the device. Also, the mail logs show that the xaps plugin did not finish the socket connection cleanly:
```
Oct 30 00:32:52 jupiter dovecot: lda(andrew): Debug: xaps_plugin_init
Oct 30 00:32:52 jupiter dovecot: lda(andrew): Debug: xaps_transaction_begin
Oct 30 00:32:52 jupiter dovecot: lda(andrew): Debug: xaps_transaction_begin
Oct 30 00:32:52 jupiter dovecot: lda(andrew): Debug: xaps_save_finish
Oct 30 00:32:52 jupiter dovecot: lda(andrew): Debug: xaps_transaction_commit
Oct 30 00:32:52 jupiter dovecot: lda(andrew): Error: write(/var/run/dovecot/xapsd.sock) failed: Broken pipe
Oct 30 00:32:52 jupiter dovecot: lda(andrew): Error: cannot notify
Oct 30 00:32:52 jupiter dovecot: lda(andrew): msgid=<REDACTED@mail.gmail.com>: saved mail to INBOX
Oct 30 00:32:52 jupiter dovecot: lda(andrew): Debug: xaps_plugin_deinit
```
Any tips on how to debug this? Is there a simple way to see if the notification is successfully being sent to Apple's servers? Right now the code says that it does not check for errors.

Thanks,
Andrew.

**Comment by heinemml** [comment]
`[DEBUG] Returning success:` is actually all you will get when it sent the push successfully to Apple. It looks the same on my working setup.

This: st3fan/dovecot-xaps-plugin#4  seems related to your Broken pipe issue. What's your dovecot version?

**Comment by anaoum** [comment]
Thanks @heinemml. You are right about the broken pipe issue, I was using dovecot 2.2.9, but I upgraded to 2.2.18 to solve this problem.

One thing that does not make sense is why upgrading dovecot has caused notifications to start working. The daemon logs debug show that the push notification is sent regardless of the version of dovecot I am running. But the notifications were only being sent to my device with dovecot 2.2.18. I recreated this 3 separate times using a fresh virtual machine. 

Is there any reason the daemon does not check for errors after submitting the notification? The APNS Client struct provides a FailedNotifs channel..

**Comment by anaoum** [comment]
Furthermore, I just tested Dovecot 2.2.13 (on Debian 8) and it too is working as expected without the broken pipe issue in 2.2.9. Looking through the Dovecot release notes I have not been able to narrow down the change that fixes the problem, but it seems as though it happens somewhere between 2.2.9 and 2.2.13.
