### ISSUE TITLE
empty certificate.pem

### ISSUE THREAD

**Issue by sanderkwantes** [st3fan/dovecot-xaps-daemon#19]
When extracting the key.pem and certificate.pem from the .p12 file it seems the certificate.pem is empty.

>openssl pkcs12 -in PushEmail.p12 -nocerts -nodes -out key.pem
>openssl pkcs12 -in PushEmail.p12 -clcerts -nokeys -out certificate.pem

The key.pem is generated with content but the certificate.pem is not.
I might be doing something wrong, but i have repeatedly followed the instructions.
I'm on OSX El Capitan.

**Comment by puzich** [comment]
Same problem here, actually...

**Comment by puzich** [comment]
Please read the section, what to export again. I've done the same mistake and only exported the key, not the appropriate certificate.

**Comment by sanderkwantes** [comment]
Thanks, reading again solved the issue for me! I guess i just searched for com.apple.servermgrd.apns.mail and exported that. For others facing this issue: The certificate that needs to be exported starts with 'APSP:' and contains this private key: 'com.apple.servermgrd.apns.mail'
