### ISSUE TITLE
push not working (no errors on dovecot side)

### ISSUE THREAD

**Issue by bmansvk** [st3fan/dovecot-xaps-daemon#21]
I installed the software according to documentation (dovecot module and xapsd-daemon, extracted certificate from OS X server / working connection to apple push server). 

I see no errors in the log, everything seems to be working. But no push is received by the iOS device.

This is the log from the xaps-daemon:
2016/04/18 17:48:49 [DEBUG] Accepted a connection
2016/04/18 17:48:49 [DEBUG] Received request: NOTIFY dovecot-username="mhostinsky"      dovecot-mailbox="INBOX"
2016/04/18 17:48:49 [DEBUG] Sending notification to 023C540F-6BA7-4D15-AF27-6FAE230EEF8D / C7E48933EFC239A633FB56846C148B9260C79D9925732A683C0272F4C9436D16
2016/04/18 17:48:49 [DEBUG] Sending notification to E2666B84-A0EF-4883-A745-7AE01BB23C8E / C7E48933EFC239A633FB56846C148B9260C79D9925732A683C0272F4C9436D16
2016/04/18 17:48:49 [DEBUG] Sending notification to 79D8C83C-70A6-4253-AAE0-6A9E73921E9A / CCDB9BA57CB6C5818ED5972DAE03CC03809D93E1849A192BEBFF26DDBE488444
2016/04/18 17:48:49 [DEBUG] Returning success:

I have several iOS devices configured, but it didn't work either with one device.

Is this software still functional?

**Comment by Antwan86** [comment]
Did you remove the mail accounts and reinstalled them ? Because I had to do it to make sure they register properly.
Also check the registry json db to ensure your devices appear there.

**Comment by heinemml** [comment]
First to your last question: Yes, the plugin still works fine (at least on my server).

Looks to me like this is one of this cases where you depend on Apples Push Service to get it right. This usually solves itself after some hours/days. I had the same strange behavior when I first set this up.

Your log output indicates that you are delivering notifications for 3 devices to Apple. So from there on it depends on their push service.

Voodoo Tips that might improve the situation or might do nothing at all:
* Reboot the receiving devices (But as they have registered themselves to your server they seem to be aware that the mailserver knows Push)
* Add your mail domains to the OS X Server instance that generated the cert (my theory is that the OS X Mailserver is passing information about "known domains" to Apple. I never verified this.)

**Comment by bmansvk** [comment]
I solved it. It seems that there is an issue with Dovecot (2.2.10) shipped with Centos7. I upgraded Dovecot to 2.2.19 (from GF Repo) and it works!

This issue someone mentioned in some issue of xaps-plugin.

So Dovecot 2.2.15 and later should work.

BTW, xaps is totally awesome. Finally I found solution for push email using native iOS client.
