### ISSUE TITLE
Helper Scripts

### ISSUE THREAD

**Issue by bakerjalexander** [st3fan/dovecot-xaps-daemon#23]
I run the daemon with screen and use monit to restart if necessary.  Here's my script, with monit 5.16, I run it from my rc.local

/usr/scripts/xapsd:
# !/bin/bash

RETVAL=0
PROG="xapsd"
EXEC="/etc/dovecot/dovecot-xaps-daemon-master/bin/$PROG"
LOGFILE="/var/log/$PROG.log"
CERTIFICATE="/etc/dovecot/apple_push_certs/certificate.pem"
DATABASE="/var/lib/$PROG/database.json"
DEBUG="true"
KEY="/etc/dovecot/apple_push_certs/key.pem"
SOCKET="/var/run/dovecot/$PROG.sock"
LOCKFILE="/var/lock/subsys/$PROG"
OPTIONS="-certificate=$CERTIFICATE -database=$DATABASE -debug=$DEBUG -key=$KEY -socket=$SOCKET"
SCREEN="/usr/bin/screen"
PS="/bin/ps"
GREP="/bin/grep"

$PS ax | $GREP -q "[b]in/xapsd" && echo "Apple-Push Daemon already up, exiting" && exit $RETVAL
$PS ax | $GREP -q "[S]CREEN -dmS $PROG" || $SCREEN -dmS "$PROG"
$SCREEN -S "$PROG" -p 0 -X stuff "$EXEC $OPTIONS >> $LOGFILE 2>&1 $(printf \\r)"

exit $RETVAL

Here's my monit config:

check process xapsd
   matching "/bin/xapsd"
   # Uncomment below with monit version > 5.17, remove /usr/scripts/xapsd from rc.local
   # onreboot start
   start program = "/usr/scripts/xapsd"
   stop  program = "/usr/bin/killall xapsd && /usr/bin/screen -S 'xapsd' -p 0 -X quit"
   if 5 restarts with 5 cycles then timeout

**Comment by m3nu** [comment]
Here is my `systemd` unit to run the daemon.

```
[Unit]
Description=Apple Push Notification Daemon for Dovecot
After=network.target

[Service]
WorkingDirectory=/opt/apple-push
ExecStart=/usr/bin/nohup dovecot-xaps-daemon/bin/xapsd -key=key.pem -certificate=certificate.pem -database=xapsd.json -socket=/var/run/dovecot/xapsd.sock -debug
Restart=on-abort
User=root

[Install]
WantedBy=multi-user.target
```

Not sure if running as root is needed. Still need to look into that part.

**Comment by bakerjalexander** [comment]
Here's my systemd, I removed the monit entry


[Unit]
Description=Apple Push Notification Daemon for Dovecot
After=network.target

[Service]
Type=forking
ExecStart=/usr/bin/bash /usr/scripts/xapsd
Restart=on-abort
User=root

[Install]
WantedBy=multi-user.target

**Comment by freswa** [comment]
I don't think this is an issue..?! If I am wrong, please feel free to reopen.
