### ISSUE TITLE
Document metadata / privacy implications

### ISSUE THREAD

**Issue by DanielDent** [st3fan/dovecot-xaps-daemon#36]
It would be nice to document what additional information Apple receives when a server is configured with this plugin.

Is the protocol basically just a wakeup command instructing the device to fetch mail?

Possibilities:
 1. Apple learns the specific times new messages are received
 2. Apple learns the specific times new messages are received, and that a stream of messages are delivered to the same account
 3. Apple learns the specific times new messages are received, and that a stream of messages are delivered to the same account, and that they are delivered to a specifically named folder (perhaps this is only relevant if other open issues are resolved)
 4. Apple learns the date, time, sender, subject, and first few lines of newly received messages

Extremely quick/cursory inspection of the source indicates the answer is likely 2 or 3, but it seems safer to ask.

I think many users would benefit from adding this information to the README or other documentation.

Thanks for your work while developing this.

**Comment by freswa** [comment]
Apple only knows that there may be messages for a device with $DeviceToken and $AccountId ready to be fetched. Furthermore they know the server-id by the certificate topic which you have to issue to make dovecot-xaps-daemon work.

If there are indeed new messages is only known by dovecot and the (iOS) client itself.

Since we send no content, this mechanism can be obfuscated to send less metadata.

@DanielDent Is this comprehensible? If yes, I will add this to the README. Thanks

**Comment by DanielDent** [comment]
Thanks @freswa for the prompt response. If I've understood you correctly, here is how I would express what you've said:

Each time a message is received, `dovecot-xaps-daemon` sends Apple a TLS-secured HTTP request, which Apple uses to send a notification over a persistent connection maintained to between the user's device and Apple's push notification servers.

The request contains the following information: a device token (used by Apple to identify which device should be sent a push notification), an account ID (used by the user's device to identify which account it should poll for new messages), and a certificate topic. The certificate topic identifies the server to Apple and is hardcoded in the certificate issued by Apple and setup in the configuration for `dovecot-xaps-daemon`.

By virtue of having made the request, Apple also learns the IP address of the server sending the push notification, and the time at which the push notification is sent by the server to Apple.

While no information typically thought of as private is directly exposed to Apple, some difficult to avoid leaks still occur. For example, Apple could correlate that two or more users frequently receive a push notification at almost the exact same time. From this, Apple could potentially infer that these users are receiving the same message. For most users this may not be a significant new loss of privacy.
"""

**Comment by freswa** [comment]
Thanks @DanielDent
