### ISSUE TITLE
New Apple Root CA question

### ISSUE THREAD

**Issue by tgrushka** [st3fan/dovecot-xaps-daemon#55]
This plugin/daemon (so far) works **great** for me on Debian 10/Dovecot 2.3.4.1! Thank you so much, this is **AWESOME!**

I noticed this in the README:
```
TODO: Does this mean we also need to pass the CA file to the xapsd process?
```

And this page: [Apple Push Notification service server certificate update](https://developer.apple.com/news/?id=7gx0a2lp)

Will the daemon keep working after 3/29? Do I need to install the CA in my server root certs, or will I need to recompile the daemon (any changes?)?

Thanks so much!

**Comment by freswa** [comment]
The daemon uses the systems CA certificates. So as long as the regarding CA is in the system CA store, the daemon shouldn't be affected by the mentioned news.
